# Аналіз даних {#introduction}

Навіщо нам потребін аналіз?
ToDO


Що потрібно знати, для того щоб займатись аналізом даних? Є три основні компоненти:
1) Знання предметної області. Це дозволяє розуміти, які проблеми потребують першочергового вирішення.
2) Знання математики та статистики. Вони дозволяють формалізувати рішення, перевести його в алгоритм та оцінити, яка ймовірність отримати результат.
3) Оскільки зараз є можливість застосовувати величезні обчислювальні потужності, тому вміння програмувати є важливим для побудови моделей.


## Процес аналізу даних 

Складається з трьох етапів. Спочатку дані потрібно підготувати, тобто зібрати, очистити та відібрати ті, які потрібні для моделі. Цей процес займає близько 90% часу. Далі ми будуємо модель та валідуємо її результати. Останній етап – це презентація результатів. Тут ми демонструємо на яке питання ми шукали відповідь, які дані використовували та що отримали в результаті. Для того щоб це зробити максимально ефективно треба витрати ще 90% часу. 

flow diagram will be here


## Статистика

Davidian та Louis пропонують наступне визначення:

> "Statistics is the science of learning from data, and of measuring, controlling, and communicating uncertainty; and it thereby provides the navigation essential for controlling the course of scientific and societal advances"  Davidian, M. and Louis, T. A., 10.1126/science.1218685.

тобто 

> Статистика -  наука про навчання на основі даних, про вимірювання, контроль та тлумачення невизначеності; має важливе значення для управління ходом наукових і соціальних досягнень.

Статистика допомагає **оцінити варіативність** та **зменшити невизначеність**.
Розрізняють описову та вивідну статистики. 

* Описова - вивчає властивості спостережуваних даних.
  + Вивідна статистика – виводимо припущення про властивості розподілу даних з яких походять спостережувані дані

З допомогою статистики можна дати відповідь на питання 

* чи є залежність між кількістю злочинів та фазою Місяця? 
 + яка ймовірність викликати Uber в Києві?
 + побудувати довірчий інтервал часу, за який ви потрапляєте на роботу
 + проводити опитування та трактувати їх результати

## Дані

* **Кількісні:** дискретні, неперервні
* **Категоріальні:** впорядковані, невпорядковані

## Рівні виміру

* Точка
* Інтервал
* Відношення

## Матриця даних

Матриця даних – стартовий елемент для аналізу даних. Зазвичай йому передує етап збору, очищення та представлення у табличному вигляді. По рядках  – респонденти, суб’єкти, учасники, спостереження
По стовпцях - xарактеристики кожного запису(змінні).  Також важливо звертати увагу на одиниці виміру а також яким чином були зібрані ці дані. Для того, щоб описати вміст цієї таблиці в більш зрозумілій формі використовують узагальнення та опис типових чи середніх значень. Для цього важливо знати тип даних.

```{r}
data("mtcars")
```

## Розвідувальний аналіз

**Розвідувальний аналіз (Exploratory Data Analysis, EDA)** використовується для того, щоб краще зрозуміти природу даних та закономірності. Для цього можемо застосовувати візуальний аналіз.

