<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title></title>
  <meta name="description" content="">
  <meta name="generator" content="bookdown 0.7 and GitBook 2.6.7">

  <meta property="og:title" content="" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="" />
  
  
  




  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="interpetation.html">

<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Передмова</a><ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#section-0.1"><i class="fa fa-check"></i><b>0.1</b> Теми:</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>1</b> Аналіз даних</a><ul>
<li class="chapter" data-level="1.1" data-path="introduction.html"><a href="introduction.html#--"><i class="fa fa-check"></i><b>1.1</b> Процес аналізу даних</a></li>
<li class="chapter" data-level="1.2" data-path="introduction.html"><a href="introduction.html#section-1.2"><i class="fa fa-check"></i><b>1.2</b> Статистика</a></li>
<li class="chapter" data-level="1.3" data-path="introduction.html"><a href="introduction.html#section-1.3"><i class="fa fa-check"></i><b>1.3</b> Дані</a></li>
<li class="chapter" data-level="1.4" data-path="introduction.html"><a href="introduction.html#-"><i class="fa fa-check"></i><b>1.4</b> Рівні виміру</a></li>
<li class="chapter" data-level="1.5" data-path="introduction.html"><a href="introduction.html#-"><i class="fa fa-check"></i><b>1.5</b> Матриця даних</a></li>
<li class="chapter" data-level="1.6" data-path="introduction.html"><a href="introduction.html#-"><i class="fa fa-check"></i><b>1.6</b> Розвідувальний аналіз</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="visualization.html"><a href="visualization.html"><i class="fa fa-check"></i><b>2</b> Візуальний аналіз</a><ul>
<li class="chapter" data-level="2.1" data-path="introduction.html"><a href="introduction.html#-"><i class="fa fa-check"></i><b>2.1</b> Типи діаграм</a><ul>
<li class="chapter" data-level="2.1.1" data-path="introduction.html"><a href="introduction.html#-"><i class="fa fa-check"></i><b>2.1.1</b> Стовпчкова діаграма</a></li>
<li class="chapter" data-level="2.1.2" data-path="visualization.html"><a href="visualization.html#----"><i class="fa fa-check"></i><b>2.1.2</b> Стовпчкова діаграма для двох змінних</a></li>
<li class="chapter" data-level="2.1.3" data-path="introduction.html"><a href="introduction.html#-"><i class="fa fa-check"></i><b>2.1.3</b> Кругова діаграма</a></li>
<li class="chapter" data-level="2.1.4" data-path="introduction.html"><a href="introduction.html#-"><i class="fa fa-check"></i><b>2.1.4</b> Точкові графіки</a></li>
<li class="chapter" data-level="2.1.5" data-path="visualization.html"><a href="visualization.html#section-2.1.5"><i class="fa fa-check"></i><b>2.1.5</b> Гістограма</a></li>
<li class="chapter" data-level="2.1.6" data-path="introduction.html"><a href="introduction.html#-"><i class="fa fa-check"></i><b>2.1.6</b> Діаграма розсіювання</a></li>
<li class="chapter" data-level="2.1.7" data-path="introduction.html"><a href="introduction.html#-"><i class="fa fa-check"></i><b>2.1.7</b> Лінійний графік</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="introduction.html"><a href="introduction.html#--"><i class="fa fa-check"></i><b>2.2</b> Як обрати графік?</a></li>
<li class="chapter" data-level="2.3" data-path="introduction.html"><a href="introduction.html#-"><i class="fa fa-check"></i><b>2.3</b> Трактування результатів</a><ul>
<li class="chapter" data-level="2.3.1" data-path="introduction.html"><a href="introduction.html#-"><i class="fa fa-check"></i><b>2.3.1</b> Парадокс Сімпсона</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="rrstudio.html"><a href="rrstudio.html"><i class="fa fa-check"></i><b>3</b> Робота з R/Rstudio</a><ul>
<li class="chapter" data-level="3.1" data-path="rrstudio.html"><a href="rrstudio.html#r--"><i class="fa fa-check"></i><b>3.1</b> R як калькулятор:</a></li>
<li class="chapter" data-level="3.2" data-path="rrstudio.html"><a href="rrstudio.html#---r"><i class="fa fa-check"></i><b>3.2</b> Типи даних в R:</a></li>
<li class="chapter" data-level="3.3" data-path="rrstudio.html"><a href="rrstudio.html#-r-"><i class="fa fa-check"></i><b>3.3</b> Типи R обєктів</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="centraltendency.html"><a href="centraltendency.html"><i class="fa fa-check"></i><b>4</b> Центральна тенденція</a><ul>
<li class="chapter" data-level="4.1" data-path="centraltendency.html"><a href="centraltendency.html#---."><i class="fa fa-check"></i><b>4.1</b> Квартилі та інтерквартильний розмах.</a></li>
<li class="chapter" data-level="4.2" data-path="introduction.html"><a href="introduction.html#-"><i class="fa fa-check"></i><b>4.2</b> Коробчата діаграма</a></li>
<li class="chapter" data-level="4.3" data-path="centraltendency.html"><a href="centraltendency.html#---"><i class="fa fa-check"></i><b>4.3</b> Дисперсія та середньоквадратичне відхилення</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="probability.html"><a href="probability.html"><i class="fa fa-check"></i><b>5</b> Ймовірність</a><ul>
<li class="chapter" data-level="5.1" data-path="introduction.html"><a href="introduction.html#--"><i class="fa fa-check"></i><b>5.1</b> Ймовірність однієї події</a></li>
<li class="chapter" data-level="5.2" data-path="introduction.html"><a href="introduction.html#--"><i class="fa fa-check"></i><b>5.2</b> Ймовірність кількох подій</a></li>
<li class="chapter" data-level="5.3" data-path="introduction.html"><a href="introduction.html#-"><i class="fa fa-check"></i><b>5.3</b> Теорема Байеса</a></li>
<li class="chapter" data-level="5.4" data-path="introduction.html"><a href="introduction.html#-"><i class="fa fa-check"></i><b>5.4</b> Класичні розподіли</a></li>
<li class="chapter" data-level="5.5" data-path="introduction.html"><a href="introduction.html#-"><i class="fa fa-check"></i><b>5.5</b> Нормальний розподіл</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="inferentialstats.html"><a href="inferentialstats.html"><i class="fa fa-check"></i><b>6</b> Вивідна статистика</a><ul>
<li class="chapter" data-level="6.1" data-path="introduction.html"><a href="introduction.html#--"><i class="fa fa-check"></i><b>6.1</b> Центральна гранична теорема</a></li>
<li class="chapter" data-level="6.2" data-path="introduction.html"><a href="introduction.html#-"><i class="fa fa-check"></i><b>6.2</b> Довірчий інтервал</a></li>
<li class="chapter" data-level="6.3" data-path="introduction.html"><a href="introduction.html#-"><i class="fa fa-check"></i><b>6.3</b> Розмір вибірки</a></li>
<li class="chapter" data-level="6.4" data-path="visualization.html"><a href="visualization.html#----"><i class="fa fa-check"></i><b>6.4</b> Довірчий інтервал для середнього значення</a></li>
<li class="chapter" data-level="6.5" data-path="visualization.html"><a href="visualization.html#----"><i class="fa fa-check"></i><b>6.5</b> Покроковий план побудови довірчого інтервалу</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="hypothesistest.html"><a href="hypothesistest.html"><i class="fa fa-check"></i><b>7</b> Тестування гіпотез</a></li>
<li class="chapter" data-level="8" data-path="confidenceinterval.html"><a href="confidenceinterval.html"><i class="fa fa-check"></i><b>8</b> Довірчий інтервал</a><ul>
<li class="chapter" data-level="8.1" data-path="visualization.html"><a href="visualization.html#----"><i class="fa fa-check"></i><b>8.1</b> Тестування гіпотез для середнього значення</a></li>
<li class="chapter" data-level="8.2" data-path="introduction.html"><a href="introduction.html#-"><i class="fa fa-check"></i><b>8.2</b> інший підхід</a></li>
<li class="chapter" data-level="8.3" data-path="centraltendency.html"><a href="centraltendency.html#---"><i class="fa fa-check"></i><b>8.3</b> Тестування гіпотез для пропорції</a></li>
<li class="chapter" data-level="8.4" data-path="centraltendency.html"><a href="centraltendency.html#---"><i class="fa fa-check"></i><b>8.4</b> Покроковий план тестування гіпотез</a></li>
<li class="chapter" data-level="8.5" data-path="visualization.html"><a href="visualization.html#----"><i class="fa fa-check"></i><b>8.5</b> Помилки І та ІІ типу</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="ml.html"><a href="ml.html"><i class="fa fa-check"></i><b>9</b> Машинне навчання</a></li>
<li class="chapter" data-level="10" data-path="interpetation.html"><a href="interpetation.html"><i class="fa fa-check"></i><b>10</b> Трактування результатів</a><ul>
<li class="chapter" data-level="10.0.1" data-path="interpetation.html"><a href="interpetation.html#--1"><i class="fa fa-check"></i><b>10.0.1</b> Парадокс Сімпсона</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="linearreression.html"><a href="linearreression.html"><i class="fa fa-check"></i><b>11</b> Лінійна регресія</a><ul>
<li class="chapter" data-level="11.1" data-path="introduction.html"><a href="introduction.html#--"><i class="fa fa-check"></i><b>11.1</b> Коваріація та кореляція</a></li>
<li class="chapter" data-level="11.2" data-path="introduction.html"><a href="introduction.html#-"><i class="fa fa-check"></i><b>11.2</b> Лінійна регресія</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./"></a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="linearreression" class="section level1">
<h1><span class="header-section-number">Розділ 11</span> Лінійна регресія</h1>
<div id="--" class="section level2">
<h2><span class="header-section-number">11.1</span> Коваріація та кореляція</h2>
<p>До цього часу ми працювали над аналізом однієї змінної. Тепер ми перейдемо до аналізу взаємозв’язків між двома змінними.</p>
<p><strong>Коваріація</strong> – міра лінійної залежності двох випадкових величин одна від одної. <strong>Кореляція</strong> – зважена версія коваріації.</p>
<p>Коефіцієнт кореляції (ще має назву коефіцієнт Пірсона) обчислюється за формулою:</p>
<p><span class="math display">\[r = \frac{cov(X,Y)}{\sqrt{var(X)} \sqrt{var(Y)}} = \frac {\sum{(x_i - \bar{x})(y_i - \bar{y})}}{\sqrt{\sum{(x_i - \bar{x})^2}\sum{(y_i - \bar{y})^2}}}\]</span></p>
<p>В R коефіцієнт для обчислення коефіцієнта кореляції використовується функція <code>cor</code>, яка по замовчуванню рахує коефіцієнт кореляції Пірсона(є й інші коефіцієнти кореляції).</p>
<p>Абсолютне значення коефіцієнта кореляції дає уявлення про силу лінійного зв’язку між двома змінними. Знак коефіцієнта вказує напрямок зв’язку. Коефіцієнт кореляції набуває значень [– 1,1]. Якщо коефіцієнт близький до 1 - говорять про сильну позитивну кореляцію, до -1 про сильну негативну. Значення коефіцієнта близькі до 0 вказують на відсутність лінійної кореляції.</p>
<p>Властивості коефіцієнта кореляції:</p>
<ul>
<li>коефіцієнт кореляції не змінюється при зміні одиниць виміру(наприклад від кілограм до грам)</li>
<li>коефіцієнт кореляції є симетричним r(x, y) = r(y, x)</li>
<li>коефіцієнт кореляції чутливий до викидів</li>
</ul>
</div>
<div id="-" class="section level2">
<h2><span class="header-section-number">11.2</span> Лінійна регресія</h2>
<p>Якщо коефіцієнт кореляції дає нам розуміння чи є лінійна залежність між двома змінними, то <em>лінійна регресія</em> дає модель для оцінки як зміниться одна змінна при зміні іншої. Наприклад, може визначити, як вага дорослої анаконди при зміні її довжини.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">anaconda &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;anaconda.dat&quot;</span>, <span class="dt">sep=</span><span class="st">&quot;&quot;</span>, <span class="dt">header =</span> <span class="ot">FALSE</span>)
<span class="kw">colnames</span>(anaconda) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Height&quot;</span>, <span class="st">&quot;Weight&quot;</span>, <span class="st">&quot;Sex&quot;</span>)</code></pre></div>
<p>Побудуємо графік розсіювання для наших даних:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(anaconda, <span class="kw">aes</span>(<span class="dt">x=</span>Height, <span class="dt">y=</span>Weight)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">col=</span><span class="st">&quot;blue&quot;</span>)</code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-68-1.png" width="672" /></p>
<p>На основі цього графіка, можемо припустити, що є позитивна лінійна залежність між довжиною та вагою дорослих анаконд. Знайдемо коефіцієнт кореляції:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cor</span>(anaconda<span class="op">$</span>Height, anaconda<span class="op">$</span>Weight)</code></pre></div>
<pre><code>## [1] 0.9613875</code></pre>
<p>Дійсно, ці дві змінні мають сильну позитивну лінійну залежність.</p>
<p>Лінійна регресія передбачає що ми побудуємо лінію, яка якнайкраще описуватиме наші дані.</p>
<p>Формула цієї лінії:</p>
<p><span class="math display">\[\hat y = ax + b\]</span></p>
<p>де x - <em>незалежна змінна</em> (в нашому прикладі це довжина), y - <em>залежна змінна</em> (вага анаконд).</p>
<p>a - це кут нахилу цієї прямої (<code>slope</code>)</p>
<p>b - точка перетину з <code>y</code>, де <code>x = 0</code> (<code>intercept</code>)</p>
<p>Як знайти цб лінію? Через ці точки можна провести безліч ліній, один з найчастіше вживаних для побудови “найкращої лінії” - <strong>метод найменших квадратів</strong>. Серед всіх ліній, найкращою ввжається та, сума квадратів залишків якої є найменшою.</p>
<p><strong>Залишок</strong> - ці різниця між справжнім значенням залежної змінної y та тим, яке передбачає моделі, тобто <span class="math inline">\(y - \hat y\)</span>. Відповідно в процесі знаходження найкращої ліній ми мінімізуємо <span class="math inline">\(\sum{(y - \hat y)^2}\)</span>.</p>
<p>Є формули для обчислення коефіцієнтів a та b. Однак ми скиристаємось функціоналом R.</p>
<p>Для знаходження найкращої лінії, яка й буде нашою моделлю, будемо використовувати функцію <code>lm</code>. Вказуємо формулу залежності <code>Weight ~ Height</code> означає, шо ми будуємо лінійну модель залежності змінної <code>Weight</code> від змінної <code>Height</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">prediction_model &lt;-<span class="st"> </span><span class="kw">lm</span>(Weight <span class="op">~</span><span class="st"> </span>Height, <span class="dt">data=</span>anaconda)</code></pre></div>
<p>Для оцінки результатів лінійної моделі використовується функція <code>summary</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(prediction_model)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Weight ~ Height, data = anaconda)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -9.2050 -3.9127 -0.2454  1.9430 16.8067 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -50.730584   2.946034  -17.22   &lt;2e-16 ***
## Height        0.253047   0.009857   25.67   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 5.754 on 54 degrees of freedom
## Multiple R-squared:  0.9243, Adjusted R-squared:  0.9229 
## F-statistic:   659 on 1 and 54 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Давайте подивимось, яку інформацію про модель ми отримали:</p>
<div class="figure">
<img src="lm.png" />

</div>
<p>Значення коефіцієнта <code>Height</code>(відповідає <code>a</code> в загальній моделі <span class="math inline">\(\hat y = ax +b\)</span>) становить <code>0.253</code>,<br />
<code>Intercept</code>(відповідає<code>b</code>) становить <code>-50.73</code>. Тобто формула залежності ваги анаконди від її довжини: <span class="math display">\[\hat Weight = 0.253 Height -50.73 \]</span></p>
<p>Це означає, що при збільшенні довжини на 1 см, вага збільшується на 0.253 кг або ж 253 грами.</p>
<p>Також досить корисним для трактування результатів є коефіцієнт <span class="math inline">\(R^2\)</span>. Рахується як квадрат коефіцієнта кореляції, тому має значення від 0 до 1. Основна його цінність у тому, що він говорить, який відсоток варіативності залежної змінної пояснюється лінійною моделлю. Відповідно залишок пояснюється змінними, які не включені в модель. Для лінійної моделі залежності ваги анаконд від їх довжини залишок складає 8%. До змінних, які можуть покращити модель належить, наприклад, стать або вік цих анаконд.</p>
<p>Також в <code>ggplot2</code> (як і в базовому функціоналі R) лінію регресії можна додати до графіка розсіювання:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(anaconda, <span class="kw">aes</span>(<span class="dt">x=</span>Height, <span class="dt">y=</span>Weight)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">col=</span><span class="st">&quot;blue&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="dt">se=</span><span class="ot">FALSE</span>)</code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-72-1.png" width="672" /></p>
<p>Умови для побудови лінійної регресії:</p>
<ul>
<li>Лінійність (тобто наявність лінійної залежності між незалежною та залежною змінною)</li>
<li>Нормальний розподіл залишків</li>
<li>Гомоскедастичність (стала варіативність залишків)</li>
</ul>
<p>За цим посиланням <a href="https://gallery.shinyapps.io/slr_diag/" class="uri">https://gallery.shinyapps.io/slr_diag/</a> ви можете змоделювати дані з різними типами залежності та дослідити, як при цьому будуть виглядати лінія регресії, коефіцієнт кореляції, <span class="math inline">\(R^2\)</span>, та як виглядає розподіл залишків.</p>
<p><strong>Екстраполяція</strong> – застосування моделі, до діапазону даних., для якого моделювання не проводилося. Сам підхід гарно ілюстрює XKCD комікс <a href="http://xkcd.com/605/" class="uri">http://xkcd.com/605/</a>. Якщо ви сьогодні вийшли заміж, то вчора у вас було 0 чоловіків, сьогодні 1, через місяць 30, а через рік 365 :) <img src="extrapolating.png" /></p>
<p>Важливо уникати екстраполяції, оскільки ми не знаємо, як зміниться тренд для даних, яких ми ще не бачили.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="interpetation.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
